version: '3.7'

services:

  postgres:
    image: postgres:13.2
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    profiles:
      - core

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    profiles:
      - core
      - percolator

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_MESSAGE_MAX_BYTES: 32768
      KAFKA_CREATE_TOPICS: "account-domain-event,book-domain-event,search-preference-domain-event"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    profiles:
      - core
      - percolator

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    container_name: "elasticsearch"
    environment:
      - cluster.name=book-cluster
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"
    profiles:
      - percolator